### ISSUE TITLE
format of key (etc) in yaml

### ISSUE THREAD

**Issue by writecarl** [appleboy/drone-sftp-cache#16]
I have tried storing the ssh-rsa key in several ways in the yaml file.   the key directly, key with 'ssh-rsa key user'   with and without quotes, as well as the location of a file containing the info.   I always get the same answer:

ssh: no key found

can you please enlighten me on what these entries should look like?  

thank you!

**Comment by trondd555** [comment]
This is confusing me as well.  I am trying to pass the key as a secret.
