### ISSUE TITLE
Fall back to target branch when cache is missing

### ISSUE THREAD

**Issue by mithrandi** [appleboy/drone-sftp-cache#25]
For a new branch (eg. PR), the cache will obviously not exist for the first test run. The old Drone caching behaviour was to try fall back to the target branch's cache, and this will generally be much faster than running an uncached build the first time for every PR. Would it be possible for `drone-sftp-cache` to do this?

**Comment by appleboy** [comment]
please add `ignore_branch` attribute.

```diff
  restore_cache:
    image: appleboy/drone-sftp-cache
    restore: true
    mount: [ cache, node_modules, .yarn-cache ]
+   ignore_branch: true
```

I am sure that the old Drone caching behaviour **wasn't** to try fall back to the target branch's cache.

**Comment by mithrandi** [comment]
Would this mean a single cache is shared between every branch? That will probably work for now, but it's not quite what I would want in general (if something goes wrong with the cached data, PR builds shouldn't cause problems for my master builds, for example).

**Comment by appleboy** [comment]
> Would this mean a single cache is shared between every branch?

Yes

> (if something goes wrong with the cached data, PR builds shouldn't cause problems for my master builds, for example)

Please add text `[cache skip]` or `[skip cache]` in commit message to ignore restore cache. The drone will rebuild new cache data after building success without restoring old cache data.

**Comment by mithrandi** [comment]
I noticed that I also had to use absolute paths for the cache mounts, eg:
```
mount: ['/drone/pip-cache']
```
Otherwise the cached tar file contains the full path in it like `drone/src/github.com/fusionapp/fusion-index/commit/6f010f5cedf3f8b227752cbd57f944a869329963/pip-cache` and then when building a new commit, restoring the cache doesn't put the directory into the git checkout for that commit. Am I doing something wrong here? (Sorry for the support-ish questions, I'll probably take this to the forums if I run into more issues)

**Comment by mithrandi** [comment]
I think my previous issue was a Drone bug and should be fixed by https://github.com/drone/drone/commit/ef4ed73179453f98e88cff20bdbdb70be2617a94. For PR builds I'm just not rebuilding the cache to avoid issues caused by bad PRs (or deliberate attacks, etc.) which I guess is good enough for most cases.
